org: peerkatserverless
app: python-serverless-xls20
service: python-serverless-v2

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  region: eu-west-2
  iam:
    role: arn:aws:iam::366877760811:role/lambda-role-peerkat-nft-data-serverless
  runtime: python3.8
  layers:
    - arn:aws:lambda:eu-west-2:770693421928:layer:Klayers-p38-pandas:10
  architecture: x86_64

package:
  patterns:
    - '!venv/**'
    - '!data/**'
    - '!node_modules/**'
    - '!.flake8'
    - '!.gitignore'
    - '!Makefile'
    - '!*.json'
    - '!*.csv'
    - '!*.js'
    - '!example.py'
    - '!README.md'
    - '!pyproject.toml'
    - '!requirements-dev.txt'
    - '!env.example'
    - '!env.local'
    - '!logger.log'

functions:
  issuers-nft-dumps:
    handler: handlers.issuers_nft_dumps
    events:
      # Invoke Lambda function every hour
      - schedule: rate(1 hour)
    timeout: 900
#  issuers-nft-dump:
#    handler: handlers.issuers_nft_dumps
#    name: issuers-nft-dump-${sls:stage}
#    timeout: 900
#  issuers-taxon-dump:
#    handler: handlers.issuers_taxon_dumps
#    name: issuers-taxon-dump-${sls:stage}
#    timeout: 900


plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin